version: '2'

services:
  # SQL and document data store
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: api

  # API
  express-api-es6-starter:
    build: ./
    hostname: api
    volumes:
      - ./:/app/
      - .env.docker:/app/.env
    ports:
      - "8848:8848"
    entrypoint: /bin/sh
    command: -c "sleep 5 && yarn migrate && yarn seed && yarn start:dev"
    depends_on:
      - db
      - redis

  # Distributed in-memory cache
  redis:
    image: redis:4.0.6-alpine
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    user: redis

volumes:
    db_data:
    redis:

